### ISSUE TITLE
How does this compare to GitHub Flavored?

### ISSUE THREAD

**Issue by trusktr** [rsms/markdown-wasm#1]
Nice project! I'm curious to know the differences. Thanks!

**Comment by mity** [comment]
There is a [CommonMark specification](https://spec.commonmark.org/0.29/) and its reference implementation [Cmark](https://github.com/commonmark/cmark).

Github forked Cmark as [Cmark-gfm](https://github.com/github/cmark-gfm) and added their extensions there. (And added docs of the extension into a fork of the specification, see https://github.github.com/gfm/)

[MD4C](https://github.com/mity/md4c) (the parser used under the hood of this project) is fully compliant to CommonMark specs as well, and it also implements all the Github's extensions as described in that documentation. However the description of those extensions is much less detailed then the original CommonMark specification so in some specific corner case the behavior is little bit more likely to differ then in the core features.

Also note that Github does some additional processing (outside the cmark-gfm code) to turn e.g. `#123` into a link to Github issues etc. MD4C naturally does not do that at all.

**Comment by trusktr** [comment]
Cool, thanks! I'm using [Docsify](https://docsify.js.org/#/) to create a static doc site based on Markdown files (the markdown files are served statically). So I'm thinking it'd be neat to replace the JS markdown renderer with this WebAssembly renderer for speed.
