### ISSUE TITLE
UTF-8 support should likely be enabled in MD4C.

### ISSUE THREAD

**Issue by mity** [rsms/markdown-wasm#2]
Hello, MD4C author here.

Just noticed in the demo that reference links are not handled properly with the respect to non-ASCII case-insensitive label matching, so for example:

``` Markdown
[á]: /url
[Á]
```

is rendered as a literal

``` Html
<p>[Á]</p>
```

instead as a link.

You might perhaps want to use `-DMD4C_USE_UTF8` to remedy that. (See https://github.com/mity/md4c#inputoutput-encoding for more info.)

**Comment by mity** [comment]
Update: I have just changed the default to be the UTF-8, even when not built with `CMakeLists.txt` provided by MD4C. (https://github.com/mity/md4c/commit/64bf660aabd3fb1e4f0ae879a7beabd0cbbbefb3)

So either use the macro or update `md4c.c` file.

**Comment by rsms** [comment]
Nice! Thank you for the information :–)

**Comment by rsms** [comment]
Release v1.1.0 now uses `MD4C_USE_UTF8`
