### ISSUE TITLE
Unable to use with Svelte-kit

### ISSUE THREAD

**Issue by saiabishek1** [rsms/markdown-wasm#20]
Hi,

First off, thanks a lot for this module!

I'm trying to use this in Svelte-kit. I got it working in development mode locally after spending a few hours trying to understand and modify `markdown.es.js`. But while building for deployment I get this error -
```
[vite:worker] UMD and IIFE output formats are not supported for code-splitting builds.
``` 
Do you know how I can resolve this?

**Comment by morriswinkler** [comment]
did you get it to work in the end
