### ISSUE TITLE
Deno support?

### ISSUE THREAD

**Issue by linux-china** [rsms/markdown-wasm#6]
Any plan to add Deno support for markdown-wasm, and Deno developer can use this module to render Markdown quickly. 

Now I  have following Deno typescript code, such as demo.ts 

```typescript
import * as markdown from "https://raw.githubusercontent.com/rsms/markdown-wasm/master/dist/markdown.es.js";
await markdown.ready
console.log(markdown.parse("# hello\n*world*"))
```

I got the error with `deno run demo.ts`

```
Download https://raw.githubusercontent.com/rsms/markdown-wasm/master/dist/markdown.es.js
Check file:///Users/xxxx/demo.ts
error: Uncaught ReferenceError: document is not defined
    at https://raw.githubusercontent.com/rsms/markdown-wasm/master/dist/markdown.es.js:1:1908
```

Is it possible to produce a js file for Deno?  such as markdown.deno.js, and the code alike following:   

```typescript
import {parse} from "https://denopkg.com/rsms/markdown-wasm/dist/markdown.deno.js";
console.log(parse("# hello\n*world*"))
```

**Comment by linux-china** [comment]
I find a way to support Deno.   Add deno build in wasmc.js:  

```
module({ ...m,
  name:   "markdown-deno",
  out:    outdir + "/markdown.deno.js",
  embed:  true,
  format: "es",
})
```

then add `var document = {};'   at the beginning of markdown.deno.js.

**Comment by rsms** [comment]
Thanks! Please remember to add the license for markdown-wasm and md4c in your repo at https://github.com/linux-china/markdown-wasm since it's public, to avoid legal trouble :–)

Q: Did you close this issue by accident or did you change your mind? If the latter, care to elaborate?
